[package]
name = "bombon-transformer"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.83"
clap = { version = "4.5.4", default-features = false, features = ["std", "derive"] }
cyclonedx-bom = "0.5.0"
itertools = "0.12.1"
serde = { version = "1.0.201", features = [ "derive" ] }
serde_json = "1.0.117"
sha2 = "0.10.8"
uuid = "1.8.0"
base64 = "0.21.7"

[lints.rust]
unsafe_code = "forbid"

[lints.clippy]
all = { level = "deny" }
pedantic = { level = "deny" }
unwrap_used = { level = "deny" }
expect_used = { level = "deny" }
