name: "Run nix flake check"

on:
  push:
    branches: [main]
  pull_request:
  merge_group:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v24
      - uses: DeterminateSystems/magic-nix-cache-action@v2
        with:
          diagnostic-endpoint: ""
      - run: nix flake check
